### ISSUE TITLE
Error trying to build KADAS Albireo 

### ISSUE THREAD

**Issue by ffarkas** [sourcepole/kadas-albireo#4]
I get the following errors during the building attempt:
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"ms-windows/mingwbuild.sh\": permission denied": unknown.`

I proceeded according to KADAS Manuals and used the following command: 
`sudo docker run -v $PWD:/workspace sourcepole/kadas-mingw-buildenv ms-windows/mingwbuild.sh`

**Comment by manisandro** [comment]
This is an issue with the docker daemon, not with the container or in other ways related to KADAS Albireo. (There are various resolution suggestions if you google the error).
