### ISSUE TITLE
Trying to build using docker image

### ISSUE THREAD

**Issue by Findus79** [sourcepole/kadas-albireo#5]
Followed your steps (using Windows here), resulting in the following error:

`standard_init_linux.go:190: exec user process caused "no such file or directory"`

Is there an error in the mingwbuild.sh scripts?

**Comment by Findus79** [comment]
> Followed your steps (using Windows here), resulting in the following error:
> 
> `standard_init_linux.go:190: exec user process caused "no such file or directory"`
> 
> Is there an error in the mingwbuild.sh scripts?

I could fix the error. It was git on Windows converting all line-endings. Now it starts building, but fails with this error:

`error: /workspace/build_mingw64_qt5/src/core/qgsapplication.cpp: No such file or directory`

**Comment by pka** [comment]
See https://github.com/kadas-albireo/kadas-albireo2 for an improved build envirnoment.
