### ISSUE TITLE
installation 

### ISSUE THREAD

**Issue by szlosu** [sourcepole/kadas-albireo#6]
Hi!
I'm not familliar with programming so I need help.
This application looks interesting, and I wanted to try it.
Can anybody tell me how can I install this application? And if it's possible for everyone to use it? I've read that it was created especially for army users.

**Comment by manisandro** [comment]
You currently need to build it from source, but kadas2 [1] will soon have downloadable CI build artifacts. The core functionality should be usable for any user looking for a simplified GIS application.

[1] https://github.com/kadas-albireo/kadas-albireo2

**Comment by szlosu** [comment]
Thanks for the answer! ;)

I've found the instruction: 
https://github.com/kadas-albireo/kadas-albireo/tree/master/docker/mingw-buildenv

I did everything just as instruction said, but it doesn't work..

Below You can see lines from my docker:


Pc@Pc-Komputer MINGW64 /g/docker/Docker Toolbox
$ git clone https://github.com/sourcepole/kadas-albireo.git
Cloning into 'kadas-albireo'...
remote: Enumerating objects: 268434, done.
remote: Total 268434 (delta 0), reused 0 (delta 0), pack-reused 268434
Receiving objects: 100% (268434/268434), 506.79 MiB | 3.13 MiB/s, done.
Resolving deltas: 100% (221041/221041), done.
Checking connectivity... done.
Checking out files: 100% (11246/11246), done.

Pc@Pc-Komputer MINGW64 /g/docker/Docker Toolbox
$ cd kadas-albireo

Pc@Pc-Komputer MINGW64 /g/docker/Docker Toolbox/kadas-albireo (master)
$ docker pull sourcepole/kadas-mingw-buildenv
Using default tag: latest
latest: Pulling from sourcepole/kadas-mingw-buildenv
Digest: sha256:365db6d8125ef17fd0a1e5b33ae7cbd04412b34b949946af089b860ee7c10ed8
Status: Image is up to date for sourcepole/kadas-mingw-buildenv:latest
docker.io/sourcepole/kadas-mingw-buildenv:latest

Pc@Pc-Komputer MINGW64 /g/docker/Docker Toolbox/kadas-albireo (master)
$ docker run -v $PWD:/workspace sourcepole/kadas-mingw-buildenv ms-windows/ming
wbuild.sh
G:\docker\Docker Toolbox\docker.exe: invalid reference format: repository name m
ust be lowercase.
See 'G:\docker\Docker Toolbox\docker.exe run --help'.

Pc@Pc-Komputer MINGW64 /g/docker/Docker Toolbox/kadas-albireo (master)
$ docker run -v %CD%:/workspace sourcepole/kadas-mingw-buildenv ms-windows/ming
wbuild.sh
G:\docker\Docker Toolbox\docker.exe: Error response from daemon: create %CD%: "%
CD%" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA
-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute p
ath.
See 'G:\docker\Docker Toolbox\docker.exe run --help'.

Pc@Pc-Komputer MINGW64 /g/docker/Docker Toolbox/kadas-albireo (master)
$

Can You help with installation process?

**Comment by manisandro** [comment]
You are running this from a mingw shell, so you'll need to use `$PWD` instead of `%CD%`, or just write out the path directly.

But I'd really recommend you waited for the KADAS 2 CI builds.

**Comment by szlosu** [comment]
I still don't get it
Let's see if I'm doing it correctly:
First:
$ git clone https://github.com/sourcepole/kadas-albireo.git
Next step:
$ cd kadas-albireo
Next:
$ docker pull sourcepole/kadas-mingw-buildenv

And now what should I do? 
I need to write this:
$ docker run -v $PWD:/workspace sourcepole/kadas-mingw-buildenv ms-windows/mingwbuild.sh
or this:
$ docker run -v %CD%:/workspace sourcepole/kadas-mingw-buildenv ms-windows/mingwbuild.sh

or both of them?

You mentioned about using $PWD
Should I use it here instead of %CD%?
$ docker run -v %CD%:/workspace sourcepole/kadas-mingw-buildenv ms-windows/mingwbuild.sh

Can You help me with this path? I'm copletelly new :/

**Comment by manisandro** [comment]
I depends on the shell you use.

Sorry but if you really want to build from source yourself, it's up to you to familiarize yourself with the tooling.

**Comment by szlosu** [comment]
Is it possible to run this app in other (simpler) way?

**Comment by manisandro** [comment]
As soon as the CI build is set up, you'll be able to download a zip file and just run the application executable.

**Comment by szlosu** [comment]
Alright, thanks for information! 
Have a nice day ;)

**Comment by manisandro** [comment]
@szlosu You can now try the CI builds at [1]. Note that it's still pre-release. For more info about configuration etc, consult [2].

[1] https://github.com/kadas-albireo/kadas-albireo2/releases
[2] https://github.com/kadas-albireo/kadas-manuals/tree/master/technical

**Comment by szlosu** [comment]
Hi,
Thanks for your message. I downloaded those builds, but I still don't know
how to run Kadas. Can You help me with installation process?


wt., 3 gru 2019 o 11:51 Sandro Mani <notifications@github.com> napisał(a):
